version: '3'

services:
  service-users: # users service - the service that is under test
    build: ./Users
    volumes:
      - ./Users:/usr/src/app
    ports:
      - 5001:80
    environment:
      - HTTP_PROXY=service-proxy:8500 # environmental variable for http proxy

  service-proxy: # proxy service for simulating pets service
      build: ./pets-Simulator
      volumes:
        - ./pets-Simulator:/usr/src/app
      ports:
        - 8887:8888
        - 8501:8500

  service-pets: # pets service - contains a bug and causes flakiness in users service
    build: ./Pets
    volumes:
      - ./Pets:/usr/src/app
    ports:
      - 5002:8080
